name: glm-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - gawk=5.1.0=h7f98852_0
  - gettext=0.21.1=h27087fc_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libidn2=2.3.4=h166bdaf_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - mmseqs2=13.45111=h95f258a_1
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.7=h0b41bf4_1
  - pip=22.3.1=pyhd8ed1ab_0
  - python=3.10.8=h4a9ceb5_0_cpython
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2022g=h191b570_0
  - wget=1.20.3=ha35d2d1_1
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - pip:
    - absl-py==1.2.0
    - accelerate==0.14.0
    - admin-torch==0.1.0
    - cachetools==5.2.0
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - fair-esm==1.0.2
    - fairscale==0.4.10
    - filelock==3.8.0
    - fonttools==4.38.0
    - h5py==3.7.0
    - huggingface-hub==0.10.0
    - idna==3.4
    - joblib==1.2.0
    - kaleido==0.2.1
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - msgpack-python==0.5.6
    - numba==0.56.4
    - numpy==1.23.3
    - oauthlib==3.2.1
    - p2j==1.3.2
    - packaging==21.3
    - pandas==1.5.0
    - pillow==9.2.0
    - plotly==5.10.0
    - protobuf==3.19.6
    - psutil==5.9.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pynndescent==0.5.8
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pyyaml==6.0
    - regex==2022.9.13
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.1.2
    - scipy==1.9.2
    - seaborn==0.12.1
    - six==1.16.0
    - sklearn==0.0
    - tenacity==8.1.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - torch-tb-profiler==0.4.0
    - tqdm==4.64.1
    - transformers==4.22.2
    - typing-extensions==4.3.0
    - umap-learn==0.5.3
    - urllib3==1.26.12
